# Generated by Django 5.1.3 on 2025-04-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='buyer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='buyer',
            new_name='user',
        ),
    ]
