# Generated by Django 5.1.3 on 2025-04-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_buyer_cart_user_rename_buyer_wishlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='buyer',
        ),
    ]
