# Generated by Django 5.1.3 on 2025-04-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_user_cart_buyer_rename_user_wishlist_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='ordered_at',
        ),
    ]
